dakota_analytics:
  outputs:
    dev:
      type: duckdb
      path: '/app/data/analytics.duckdb'
      schema: 'main'
      threads: 4
      keepalives_idle: 0
      search_path: "main"
  target: dev
